declare module "@phosphor-icons/react" {
  import type { ComponentType, SVGProps } from "react";

  type IconWeight = "thin" | "light" | "regular" | "bold" | "fill" | "duotone";
  type IconProps = SVGProps<SVGSVGElement> & { size?: string | number; weight?: IconWeight };
  type IconComponent = ComponentType<IconProps>;

  export const ArrowRight: IconComponent;
  export const ArrowLeft: IconComponent;
  export const Bell: IconComponent;
  export const Books: IconComponent;
  export const Buildings: IconComponent;
  export const CaretDown: IconComponent;
  export const CaretRight: IconComponent;
  export const ChartBar: IconComponent;
  export const ChartLineUp: IconComponent;
  export const CheckCircle: IconComponent;
  export const Clock: IconComponent;
  export const Coins: IconComponent;
  export const Database: IconComponent;
  export const DownloadSimple: IconComponent;
  export const FileText: IconComponent;
  export const FunnelSimple: IconComponent;
  export const GearSix: IconComponent;
  export const Gauge: IconComponent;
  export const House: IconComponent;
  export const Info: IconComponent;
  export const Lightbulb: IconComponent;
  export const List: IconComponent;
  export const MagnifyingGlass: IconComponent;
  export const Robot: IconComponent;
  export const RocketLaunch: IconComponent;
  export const SealCheck: IconComponent;
  export const ShareNetwork: IconComponent;
  export const ShieldCheck: IconComponent;
  export const Sparkle: IconComponent;
  export const SquaresFour: IconComponent;
  export const SlidersHorizontal: IconComponent;
  export const TrendDown: IconComponent;
  export const TrendUp: IconComponent;
  export const Star: IconComponent;
  export const UserCircle: IconComponent;
  export const Warning: IconComponent;
  export const UsersThree: IconComponent;
  export const WarningCircle: IconComponent;
  export const Wrench: IconComponent;
  export const ArrowsOutCardinal: IconComponent;
  export const ArrowUpRight: IconComponent;
  export const BracketsCurly: IconComponent;
  export const CaretLeft: IconComponent;
  export const CirclesFour: IconComponent;
  export const Command: IconComponent;
  export const Cube: IconComponent;
  export const Desktop: IconComponent;
  export const Play: IconComponent;
  export const Moon: IconComponent;
  export const Sun: IconComponent;
  export const X: IconComponent;
}
